INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('体育教学中心', NULL, '103', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('科技史与科技考古系', NULL, '024', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('核科学技术学院', 'School of Nuclear Science and Technology', '214', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('科技传播系', 'Department of Communication of Science and Technology', '025', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('微电子学院', 'School of Microelectronics', '219', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('心理学系', NULL, '056', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('科技哲学系', '科技哲学系', '055', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('外语教学中心', NULL, '108', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('光学与光学工程系', 'Department of Optics and Optical Engineering', '038', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('纳米学院', '纳米学院', 'A15', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('数学科学学院', 'School of Mathematical Sciences', '001', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('物理学系', 'Department of Physics', '002', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('近代物理系', 'Department of Modern Physics', '004', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('电子工程与信息科学系', 'Department of Electronic Engineering and Information Science', '006', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('物理学院', 'School of Physical Sciences', '203', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('生命科学学院', 'School of Life Sciences', '207', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('生命科学与医学部', 'sm', '910', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('自动化系', 'Department of Automation', '010', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('工商管理系', 'Department of Business Management', '015', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('统计与金融系', 'Department of Statistics and Finance', '017', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('管理科学系', 'Department of Management Science', '016', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('天文学系', 'Department of Astronomy', '022', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('物理实验教学中心', NULL, '042', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('信息科学技术学院', 'School of Information Science and Technology', '210', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('网络空间安全学院', 'School of Cyber Science and Technology', '221', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('工程与应用物理系', 'Department of Engineering and Applied Physics', '048', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('大数据学院', 'School of Data Science', '229', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('环境科学与工程系（直属）', 'Department of Environmental Science and Engineering', '240', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('马克思主义学院', NULL, '220', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('教务处', 'Teaching Affairs', '601', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('管理学院', 'School of Business', '204', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('化学物理系', 'Department of Chemical Physics', '003', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('化学系', 'Department of Chemistry', '019', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('应用化学系', '应用化学系', '012', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('化学与材料科学学院', 'School of Chemistry and Materials Science', '206', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('材料科学与工程系', 'Department of Materials Science and Engineering', '014', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('高分子科学与工程系', 'Department of Polymer Science and Engineering', '020', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('计算机科学与技术系', 'Department of Computer Science and Technology', '011', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('艺术教学中心', NULL, '109', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('通识教育中心', NULL, '102', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('少年班学院', 'School of the Gifted Young', '000', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('创新创业学院', NULL, '529', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('精密机械与精密仪器系', 'Department of Precision Machinery and Instrumentation', '009', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('工程科学学院', 'School of Engineering', '209', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('热科学和能源工程系', 'Department of Thermal Science and Energy Engineering', '013', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('安全科学与工程系', 'Department of Safety Science and Engineering', '030', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('近代力学系', 'Department of Modern Mechanics', '005', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('党委人民武装部', NULL, '509', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('语言科学交叉研究中心', 'yy', '057', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('外语系', 'Department of Foreign Languages', '018', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('地球和空间科学学院', 'School of Earth and Space Sciences', '208', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('公共事务学院', '公共事务学院', '216', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('法律硕士教育中心', '法律硕士教育中心', '043', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('MPA中心1', 'MPA中心1', '041', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('火灾科学国家重点实验室', '火灾科学国家重点实验室', '232', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('合肥微尺度物质科学国家实验室（筹）', '合肥微尺度物质科学国家实验室（筹）', '234', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('附属第一医院', 'fsdyyy', '911', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('项目管理教育中心', '项目管理教育中心', '040', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('先进技术研究院', NULL, '218', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('软件学院苏州', '软件学院苏州', 'A14', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('合肥物质研究院', '合肥物质研究院', '168', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('紫金山天文台', '紫金山天文台', '170', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('软件学院合肥', '软件学院合肥', 'A13', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('长春应化所', '长春应化所', '175', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('国家同步辐射实验室', '国家同步辐射实验室', '231', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('MF中心（金融专硕）', 'MF', '050', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('国际合作与交流部', 'Office of International Cooperation', '504', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('生物医学工程学院', 'School of Biomedical Engineering', '916', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('金属所', '金属所', '169', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('图书馆', '图书馆', '302', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('MBA中心', 'MBA中心', '034', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('数学系', 'Department of mathematics', '045', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('计算与应用数学系', 'Department of Computational and Applied Mathematics', '046', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('概率统计系', 'Department of Probability and Statistics', '047', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('科技哲学系', '科技哲学系', '105', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('南京地质古生物研究所', '南京地质古生物研究所', '171', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('南京天文仪器研制中心', '南京天文仪器研制中心', '172', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('苏州纳米技术与纳米仿生研究所', '苏州纳米技术与纳米仿生研究所', '173', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('苏州生物医学工程技术研究所', '苏州生物医学工程技术研究所', '174', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('广州能源研究所', '广州能源研究所', '178', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('稀土研究院', '稀土研究院', '179', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('本科生院', 'Undergraduate College', '200', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('现代艺术中心', '现代艺术中心', '111', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('陶瓷艺术中心', '陶瓷艺术中心', '112', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('研究生院', 'Graduate School', '201', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('MPA中心', 'MPA Center', '035', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('EMBA', 'EMBA', '039', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('地球物理与空间科学技术系', 'Department of Geophysics and Space Science and Technology', '071', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('地球化学与行星科学系', 'Department of Geochemistry and Planetary Science', '072', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('电子科学与技术系', 'Department of Electronic Science and Technology', '023', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('人工智能系', 'Department of Artificial Intelligence', '026', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('信息安全', 'Information Security', '033', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('人文与社会科学学院', 'School of Humanities and Social Sciences', '211', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('艺术与科学研究中心', 'Center for Arts and Sciences', '058', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('加速器科学与工程物理系', 'Department of Accelerator Science and Engineering Physics', '051', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('等离子体物理与聚变工程系', 'Department of Plasma Physics and Fusion Engineering', '052', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('核科学与工程系', 'Department of Nuclear Science and Engineering', '053', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('计算机科学与技术学院', 'School of Computer Science and Technology', '215', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('物流工程硕士中心', '物流工程硕士中心', '044', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('环境科学与光电技术学院', 'School of Environmental Science and Optoelectronic Technology', '217', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('软件学院', 'School of Software', '225', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('理化中心', '理化中心', '241', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('学生工作部、学生工作处', 'Department of Student Affairs', '406', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('分子生物学与细胞生物学系', 'Department of Molecular Biology and Cell Biology', '008', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('神经生物学与生物物理学系', 'Department of Neurobiology and Biophysics', '021', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('系统生物学系', 'Department of Systems Biology', '032', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('基础医学院', 'School of Basic Medical Sciences', '912', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('临床医学院', 'School of Clinical Medicine', '913', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('未来技术学院', 'School of Future Technology', '999', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('工程管理中心', '工程管理中心', 'A17', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('MPA中心', 'MPA中心', 'A18', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('中国工程物理研究院', '中国工程物理研究院', 'B07', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('理科试验班', '理科试验班', 'BJ01', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('后备军官选培办', '后备军官选培办', 'W02', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES ('科技传播与科技政策系', '科技传播与科技政策系', '025(OLD)', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES (NULL, NULL, '403', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES (NULL, NULL, '323', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES (NULL, NULL, '304', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES (NULL, NULL, '603', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES (NULL, NULL, '037', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES (NULL, NULL, '503', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES (NULL, NULL, '502', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES (NULL, NULL, '500', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES (NULL, NULL, '107', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES (NULL, NULL, '226', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES (NULL, NULL, '508', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES (NULL, NULL, '404', True);
INSERT INTO tbl_department (name_cn, name_en, code, college) VALUES (NULL, NULL, '409', True);